test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

  # google:
  # service: GCS
  # credentials: <%= Rails.root.join("path/to/keyfile.json") %>
  # project: "My project"
  # bucket: "erez"





  amazon
  service: S3
  access_key_id: <%= ENV['BUCKETEER_AWS_AKIAIWZLHIXSO5QZWTYA'] %>
  secret_access_key: <%= ENV['BUCKETEER_AWS_5I/NU0jzZJG+fvCwgnNWh2yd4qLyhjCrtoiqrWaz'] %>
  region: <%= ENV['BUCKETEER_AWS_global'] %>
  bucket: <%= ENV['BUCKETEER_ffyourptrainer'] %>

