# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

p 'deleting countries'

Countrie.destroy_all




p 'Creating countries'




Countrie.create(name: "united Kingdom")
Countrie.create(name: "united states")
Countrie.create(name: "Afghanistan")
Countrie.create(name: "Albania")
Countrie.create(name: "Algeria")
Countrie.create(name: "Andorra")
Countrie.create(name: "Angola")
Countrie.create(name: "Antigua and Barbudas")
Countrie.create(name: "Argentina")
Countrie.create(name: "Armenia")
Countrie.create(name: "Australia")
Countrie.create(name: "Austria")
Countrie.create(name: "Azerbaijan")
Countrie.create(name: "The Bahamas")
Countrie.create(name: "Bahrain")
Countrie.create(name: "Bangladesh")
Countrie.create(name: "Barbados")
Countrie.create(name: "Belarus")
Countrie.create(name: "Belgium")
Countrie.create(name: "Belize")
Countrie.create(name: "Benin")
Countrie.create(name: "Bhutan")
Countrie.create(name: "Bolivia")
Countrie.create(name: "Botswana")
Countrie.create(name: "Brazil")
Countrie.create(name: "Brunei")
Countrie.create(name: "Bulgaria")
Countrie.create(name: "Burkina Faso")
Countrie.create(name: "Burundi")
Countrie.create(name: "Bosnia and Herzegovina")
Countrie.create(name: "Cabo Verde")
Countrie.create(name: "Cambodia")
Countrie.create(name: "Cameroon")
Countrie.create(name: "Canada")
Countrie.create(name: "Central African Republic")
Countrie.create(name: "Chad")
Countrie.create(name: "Chile")
Countrie.create(name: "China")
Countrie.create(name: "Colombia")
Countrie.create(name: "Comoros")
Countrie.create(name: "Congo")
Countrie.create(name: "Costa Rica")
Countrie.create(name: "Côte d’Ivoire")
Countrie.create(name: "Croatia")
Countrie.create(name: "Cuba")
Countrie.create(name: "Cyprus")
Countrie.create(name: "Czech Republic")
Countrie.create(name: "Denmark")
Countrie.create(name: "Djibouti")
Countrie.create(name: "Dominica")
Countrie.create(name: "Dominican Republic")
Countrie.create(name: "Ecuador")
Countrie.create(name: "East Timor (Timor-Leste)")
Countrie.create(name: "Egypt")
Countrie.create(name: "El Salvador")
Countrie.create(name: "Equatorial Guinea")
Countrie.create(name: "Eritrea")
Countrie.create(name: "Estonia")
Countrie.create(name: "Ethiopia")
Countrie.create(name: "Fiji")
Countrie.create(name: "Finland")
Countrie.create(name: "France")
Countrie.create(name: "Gabon")
Countrie.create(name: "The Gambia")
Countrie.create(name: "Georgia")
Countrie.create(name: "Germany")
Countrie.create(name: "Ghana")
Countrie.create(name: "Greece")
Countrie.create(name: "Grenada")
Countrie.create(name: "Guatemala")
Countrie.create(name: "Guinea")
Countrie.create(name: "Guinea-Bissau")
Countrie.create(name: "Guyana")
Countrie.create(name: "Haiti")
Countrie.create(name: "Honduras")
Countrie.create(name: "Hungary")
Countrie.create(name: "Iceland")
Countrie.create(name: "India")
Countrie.create(name: "Indonesia")
Countrie.create(name: "Iran")
Countrie.create(name: "Iraq")
Countrie.create(name: "Ireland")
Countrie.create(name: "Israel")
Countrie.create(name: "Italy")
Countrie.create(name: "Jamaica")
Countrie.create(name: "Japan")
Countrie.create(name: "Jordan")
Countrie.create(name: "Kazakhstan")
Countrie.create(name: "Kenya")
Countrie.create(name: "Kiribati")
Countrie.create(name: "Korea, North")
Countrie.create(name: "Korea, South")
Countrie.create(name: "Kosovo")
Countrie.create(name: "Kuwait")
Countrie.create(name: "Kyrgyzstan")
Countrie.create(name: "Laos")
Countrie.create(name: "Latvia")
Countrie.create(name: "Lebanon")
Countrie.create(name: "Lesotho")
Countrie.create(name: "Liberia")
Countrie.create(name: "Libya")
Countrie.create(name: "Liechtenstein")
Countrie.create(name: "Lithuania")
Countrie.create(name: "Luxembourg")
Countrie.create(name: "Macedonia")
Countrie.create(name: "Madagascar")
Countrie.create(name: "Malawi")
Countrie.create(name: "Malaysia")
Countrie.create(name: "Maldives")
Countrie.create(name: "Mali")
Countrie.create(name: "Malta")
Countrie.create(name: "Marshall Islands")
Countrie.create(name: "Mauritania")
Countrie.create(name: "Mauritius")
Countrie.create(name: "Mexico")
Countrie.create(name: "Micronesia")
Countrie.create(name: "Moldova")
Countrie.create(name: "Monaco")
Countrie.create(name: "Mongolia")
Countrie.create(name: "Montenegro")
Countrie.create(name: "Morocco")
Countrie.create(name: "Mozambique")
Countrie.create(name: "Myanmar (Burma)")
Countrie.create(name: "Namibia")
Countrie.create(name: "Nauru")
Countrie.create(name: "Nepal")
Countrie.create(name: "Netherlands")
Countrie.create(name: "New Zealand")
Countrie.create(name: "Nicaragua")
Countrie.create(name: "Niger")
Countrie.create(name: "Nigeria")
Countrie.create(name: "Norway")
Countrie.create(name: "Oman")
Countrie.create(name: "Pakistan")
Countrie.create(name: "Palau")
Countrie.create(name: "Panama")
Countrie.create(name: "Papua New Guinea")
Countrie.create(name: "Paraguay")
Countrie.create(name: "Peru")
Countrie.create(name: "Philippines")
Countrie.create(name: "Poland")
Countrie.create(name: "Portugal")
Countrie.create(name: "Qatar")
Countrie.create(name: "Romania")
Countrie.create(name: "Russia")
Countrie.create(name: "Rwanda")
Countrie.create(name: "Saint Kitts and Nevis")
Countrie.create(name: "Saint Lucia")
Countrie.create(name: "Saint Vincent and the Grenadines")
Countrie.create(name: "Samoa")
Countrie.create(name: "San Marino")
Countrie.create(name: "Sao Tome and Principe")
Countrie.create(name: "Saudi Arabia")
Countrie.create(name: "Senegal")
Countrie.create(name: "Serbia")
Countrie.create(name: "Seychelles")
Countrie.create(name: "Sierra Leone")
Countrie.create(name: "Singapore")
Countrie.create(name: "Slovakia")
Countrie.create(name: "Slovenia")
Countrie.create(name: "Solomon Islands")
Countrie.create(name: "Somalia")
Countrie.create(name: "South Africa")
Countrie.create(name: "Spain")
Countrie.create(name: "Sri Lanka")
Countrie.create(name: "Sudan")
Countrie.create(name: "Sudan, South")
Countrie.create(name: "Suriname")
Countrie.create(name: "Swaziland")
Countrie.create(name: "Switzerland")
Countrie.create(name: "Syria")
Countrie.create(name: "Taiwan")
Countrie.create(name: "Tajikistan")
Countrie.create(name: "Tanzania")
Countrie.create(name: "Thailand")
Countrie.create(name: "Togo")
Countrie.create(name: "Tonga")
Countrie.create(name: "Trinidad and Tobago")
Countrie.create(name: "Tunisia")
Countrie.create(name: "Turkey")
Countrie.create(name: "Turkmenistan")
Countrie.create(name: "Tuvalu")
Countrie.create(name: "Uganda")
Countrie.create(name: "Ukraine")
Countrie.create(name: "United Arab Emirates")
Countrie.create(name: "Uruguay")
Countrie.create(name: "Uzbekistan")
Countrie.create(name: "Vanuatu")
Countrie.create(name: "Vatican City")
Countrie.create(name: "Venezuela")
Countrie.create(name: "Vietnam")
Countrie.create(name: "Yemen")
Countrie.create(name: "Zambia")
Countrie.create(name: "Zimbabwe")























